apiVersion: apps/v1
kind: Deployment
metadata:
  name: sienti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sienti
  template:
    metadata:
      labels:
        app: sienti
    spec:
      containers:
      - image: okteto.dev/sienti:latest
        name: sienti
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e825669f-dd61-4bf2-82f1-38e3cb74c88f"
        - name: Vless_Path
          value: "/vl555ls34"
        - name: Vmess_UUID
          value: "e825669f-dd61-4bf2-82f1-38e3cb74c88f"
        - name: Vmess_Path
          value: "/vm666sl33"
        - name: Share_Path
          value: "/v2link"
